services:
  mysql:
    image: mysql:8.0
    container_name: webshop-mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=shop_database
      - MYSQL_USER=shop_user
      - MYSQL_PASSWORD=123456
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: webshop-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=mysql://shop_user:123456@mysql:3306/shop_database
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data:

    # docker compose -p webshop up -d
